# Generated by Django 3.2.19 on 2023-06-12 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tam', '0003_alter_book_table_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='table_id',
            new_name='tableid',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='user_id',
            new_name='userid',
        ),
    ]
