# Generated by Django 3.2.19 on 2023-06-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tam', '0004_auto_20230612_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='reservt',
            field=models.DecimalField(decimal_places=0, default=10, max_digits=2),
        ),
    ]
