# Generated by Django 3.2.19 on 2023-06-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tam', '0007_auto_20230614_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bkt',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
        ),
        migrations.AddField(
            model_name='table',
            name='bkt',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
        ),
    ]
