# Generated by Django 3.2.19 on 2023-06-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tam', '0009_alter_book_bkt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='bkt',
            field=models.DecimalField(decimal_places=0, default=10, max_digits=2),
        ),
    ]
