# Generated by Django 3.2.19 on 2023-06-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tam', '0010_alter_table_bkt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bkt',
        ),
        migrations.RemoveField(
            model_name='table',
            name='bkt',
        ),
        migrations.AddField(
            model_name='book',
            name='booked_table',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
        ),
        migrations.AddField(
            model_name='table',
            name='booked_table',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
        ),
    ]
