# Generated by Django 3.2.19 on 2023-06-15 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tam', '0011_auto_20230615_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='reservt',
        ),
    ]
