# Generated by Django 3.2.19 on 2023-06-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tam', '0012_remove_book_reservt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='booked_table',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='table',
            name='booked_table',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='table',
            name='reservt',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
