# Generated by Django 3.2.19 on 2023-06-29 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tam', '0013_auto_20230615_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='nos',
        ),
        migrations.RemoveField(
            model_name='table',
            name='nos',
        ),
    ]
